### ISSUE TITLE
1.12.2 Tools cant be repaired in the anvil.

### ISSUE THREAD

**Issue by PersuGames** [Squidsword/Ores-Above-Diamonds-Old#7]
Is it intended for amethyst tools to not have a repair item attached or is it a bug? If it is a oversight I'd ask if you could add black opal to also be "repairable" even though it is by default unbreakable because mods like quality tools rely on the default repair item and it can be made breakable in the config which would also make it need the feature of repairing in the anvil.
Thanks in advance!
![Przechwytywanie](https://user-images.githubusercontent.com/67759479/86499298-c404b200-bd8a-11ea-9b2d-4d1bd3848426.PNG)

**Comment by Squidsword** [comment]
This amethyst not working to repair the tools is a bug, and I'll push a patch soon fixing the issue. Does the amethyst also not work with quality tools? I think I might be able to fix your problem even with infinite durability if the mod you are using calls getRepairMaterial().

**Comment by PersuGames** [comment]
Yeah, both amethyst and black opal don't work since it tries to get the repair item for them and it can't
One more compatibility issue I found with quality tools was that sometimes items got a modifier and sometimes they didn't and it seemed completely random. For example the amethyst pickaxe didn't get the modifier at all and the black opal pickaxe did get the modifier every time. No clue what's with that.

**Comment by Squidsword** [comment]
> Yeah, both amethyst and black opal don't work since it tries to get the repair item for them and it can't

Ahhh` yea, I think I know the issue. It was some spaghetti code on my end which wasn't letting the code find the correct material for both items. ![After this, it should probably fix even though Black Opal Tools have infinite durability.](https://user-images.githubusercontent.com/30030299/86500490-6313b480-bd5f-11ea-95c2-1b2f0e588114.png) I am actually going to be adding a durability by default to Black Opal in the next patch due to a lot controversy (you can still make it infinite in the config), so that should fix the black opal problem since it will then behave like a normal tool. Thank you for the bug report! Feel free to open another issue if anything crazy happens later on.

**Comment by PersuGames** [comment]
Thanks a lot! Looking forward to the update! I'll definitely let you know if I find anything more. Have a nice day!
